/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#171d16",
        "inverse-on-surface": "#ecf3e7",
        "on-surface-variant": "#3e4a3d",
        "on-error": "#ffffff",
        "surface-container-highest": "#dde5d9",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#a72d51",
        "on-secondary-container": "#684000",
        "secondary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#f4fcf0",
        "inverse-primary": "#62df7d",
        "on-secondary": "#ffffff",
        "surface-variant": "#dde5d9",
        "tertiary-fixed-dim": "#ffb2bf",
        "outline-variant": "#bdcaba",
        "secondary": "#855300",
        "on-primary-container": "#f7fff2",
        "primary-fixed": "#7ffc97",
        "surface-dim": "#d5dcd1",
        "on-primary-fixed": "#002109",
        "error-container": "#ffdad6",
        "surface-container": "#e9f0e5",
        "on-tertiary-container": "#fffbff",
        "outline": "#6e7b6c",
        "on-secondary-fixed": "#2a1700",
        "secondary-container": "#fea619",
        "on-primary-fixed-variant": "#005320",
        "primary-container": "#00873a",
        "primary": "#006b2c",
        "background": "#f4fcf0",
        "on-surface": "#171d16",
        "surface-bright": "#f4fcf0",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#8a143c",
        "primary-fixed-dim": "#62df7d",
        "tertiary-container": "#c74668",
        "surface-tint": "#006e2d",
        "secondary-fixed-dim": "#ffb95f",
        "surface-container-high": "#e3eadf",
        "surface-container-low": "#eff6ea",
        "on-tertiary-fixed": "#3f0016",
        "tertiary-fixed": "#ffd9de",
        "inverse-surface": "#2b322b",
        "on-secondary-fixed-variant": "#653e00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "1rem",
        "stack-xs": "0.25rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
